# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hrp.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(1145, 447)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(1145, 440))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.configLayout = QtWidgets.QVBoxLayout()
        self.configLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.configLayout.setObjectName("configLayout")
        self.dataLayout = QtWidgets.QVBoxLayout()
        self.dataLayout.setContentsMargins(-1, 5, -1, 5)
        self.dataLayout.setSpacing(5)
        self.dataLayout.setObjectName("dataLayout")
        self.dataLabelLayout = QtWidgets.QHBoxLayout()
        self.dataLabelLayout.setContentsMargins(0, -1, 0, 5)
        self.dataLabelLayout.setObjectName("dataLabelLayout")
        self.dataFileLabel = QtWidgets.QLabel(self.centralwidget)
        self.dataFileLabel.setObjectName("dataFileLabel")
        self.dataLabelLayout.addWidget(self.dataFileLabel)
        self.dataFileButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataFileButton.sizePolicy().hasHeightForWidth())
        self.dataFileButton.setSizePolicy(sizePolicy)
        self.dataFileButton.setMinimumSize(QtCore.QSize(95, 30))
        self.dataFileButton.setObjectName("dataFileButton")
        self.dataLabelLayout.addWidget(self.dataFileButton)
        self.dataLayout.addLayout(self.dataLabelLayout)
        self.dataFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dataFileEdit.setObjectName("dataFileEdit")
        self.dataLayout.addWidget(self.dataFileEdit)
        self.rateFileLayout = QtWidgets.QHBoxLayout()
        self.rateFileLayout.setContentsMargins(-1, 5, -1, 5)
        self.rateFileLayout.setObjectName("rateFileLayout")
        self.rateFileLabel = QtWidgets.QLabel(self.centralwidget)
        self.rateFileLabel.setObjectName("rateFileLabel")
        self.rateFileLayout.addWidget(self.rateFileLabel)
        self.rateFileButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rateFileButton.sizePolicy().hasHeightForWidth())
        self.rateFileButton.setSizePolicy(sizePolicy)
        self.rateFileButton.setMinimumSize(QtCore.QSize(95, 30))
        self.rateFileButton.setObjectName("rateFileButton")
        self.rateFileLayout.addWidget(self.rateFileButton)
        self.dataLayout.addLayout(self.rateFileLayout)
        self.rateFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.rateFileEdit.setObjectName("rateFileEdit")
        self.dataLayout.addWidget(self.rateFileEdit)
        self.columnFormatLayout = QtWidgets.QHBoxLayout()
        self.columnFormatLayout.setObjectName("columnFormatLayout")
        self.formatLayou = QtWidgets.QVBoxLayout()
        self.formatLayou.setContentsMargins(-1, 2, -1, 2)
        self.formatLayou.setSpacing(5)
        self.formatLayou.setObjectName("formatLayou")
        self.dateColumnLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateColumnLabel.setObjectName("dateColumnLabel")
        self.formatLayou.addWidget(self.dateColumnLabel)
        self.dateColumnEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dateColumnEdit.setObjectName("dateColumnEdit")
        self.formatLayou.addWidget(self.dateColumnEdit)
        self.columnFormatLayout.addLayout(self.formatLayou)
        self.colmnLayot = QtWidgets.QVBoxLayout()
        self.colmnLayot.setContentsMargins(-1, 2, -1, 2)
        self.colmnLayot.setSpacing(5)
        self.colmnLayot.setObjectName("colmnLayot")
        self.dateFormatLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateFormatLabel.setObjectName("dateFormatLabel")
        self.colmnLayot.addWidget(self.dateFormatLabel)
        self.dateFormatEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dateFormatEdit.setObjectName("dateFormatEdit")
        self.colmnLayot.addWidget(self.dateFormatEdit)
        self.columnFormatLayout.addLayout(self.colmnLayot)
        self.dataLayout.addLayout(self.columnFormatLayout)
        self.configLayout.addLayout(self.dataLayout)
        self.datesLayout = QtWidgets.QHBoxLayout()
        self.datesLayout.setContentsMargins(-1, -1, -1, 0)
        self.datesLayout.setSpacing(5)
        self.datesLayout.setObjectName("datesLayout")
        self.startDateLayout = QtWidgets.QVBoxLayout()
        self.startDateLayout.setObjectName("startDateLayout")
        self.startDateLabel = QtWidgets.QLabel(self.centralwidget)
        self.startDateLabel.setObjectName("startDateLabel")
        self.startDateLayout.addWidget(self.startDateLabel)
        self.schLayot = QtWidgets.QHBoxLayout()
        self.schLayot.setContentsMargins(5, -1, -1, -1)
        self.schLayot.setObjectName("schLayot")
        self.startDateCBox = QtWidgets.QCheckBox(self.centralwidget)
        self.startDateCBox.setText("")
        self.startDateCBox.setObjectName("startDateCBox")
        self.schLayot.addWidget(self.startDateCBox)
        self.startDatePicker = QtWidgets.QDateEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDatePicker.sizePolicy().hasHeightForWidth())
        self.startDatePicker.setSizePolicy(sizePolicy)
        self.startDatePicker.setMinimumSize(QtCore.QSize(90, 25))
        self.startDatePicker.setObjectName("startDatePicker")
        self.schLayot.addWidget(self.startDatePicker)
        self.startDateLayout.addLayout(self.schLayot)
        self.datesLayout.addLayout(self.startDateLayout)
        self.endDateLayout = QtWidgets.QVBoxLayout()
        self.endDateLayout.setObjectName("endDateLayout")
        self.endDateLabel = QtWidgets.QLabel(self.centralwidget)
        self.endDateLabel.setObjectName("endDateLabel")
        self.endDateLayout.addWidget(self.endDateLabel)
        self.echLayout = QtWidgets.QHBoxLayout()
        self.echLayout.setContentsMargins(5, -1, -1, -1)
        self.echLayout.setObjectName("echLayout")
        self.endDateCBox = QtWidgets.QCheckBox(self.centralwidget)
        self.endDateCBox.setText("")
        self.endDateCBox.setObjectName("endDateCBox")
        self.echLayout.addWidget(self.endDateCBox)
        self.endDatePicker = QtWidgets.QDateEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endDatePicker.sizePolicy().hasHeightForWidth())
        self.endDatePicker.setSizePolicy(sizePolicy)
        self.endDatePicker.setMinimumSize(QtCore.QSize(90, 25))
        self.endDatePicker.setObjectName("endDatePicker")
        self.echLayout.addWidget(self.endDatePicker)
        self.endDateLayout.addLayout(self.echLayout)
        self.datesLayout.addLayout(self.endDateLayout)
        self.configLayout.addLayout(self.datesLayout)
        self.reportLayout = QtWidgets.QVBoxLayout()
        self.reportLayout.setContentsMargins(-1, -1, -1, 5)
        self.reportLayout.setObjectName("reportLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reportFileLabel = QtWidgets.QLabel(self.centralwidget)
        self.reportFileLabel.setObjectName("reportFileLabel")
        self.horizontalLayout.addWidget(self.reportFileLabel)
        self.reportFileBtn = QtWidgets.QToolButton(self.centralwidget)
        self.reportFileBtn.setMinimumSize(QtCore.QSize(120, 25))
        self.reportFileBtn.setObjectName("reportFileBtn")
        self.horizontalLayout.addWidget(self.reportFileBtn)
        self.reportLayout.addLayout(self.horizontalLayout)
        self.reportFileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.reportFileEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.reportFileEdit.setObjectName("reportFileEdit")
        self.reportLayout.addWidget(self.reportFileEdit)
        self.configLayout.addLayout(self.reportLayout)
        self.runTestButton = QtWidgets.QPushButton(self.centralwidget)
        self.runTestButton.setMinimumSize(QtCore.QSize(0, 30))
        self.runTestButton.setObjectName("runTestButton")
        self.configLayout.addWidget(self.runTestButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.configLayout.addItem(spacerItem)
        self.mainLayout.addLayout(self.configLayout)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.mainLayout.addItem(spacerItem1)
        self.strategyLayout = QtWidgets.QVBoxLayout()
        self.strategyLayout.setObjectName("strategyLayout")
        self.financeLayout = QtWidgets.QHBoxLayout()
        self.financeLayout.setObjectName("financeLayout")
        self.moneyLayout = QtWidgets.QVBoxLayout()
        self.moneyLayout.setObjectName("moneyLayout")
        self.moneyLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moneyLabel.sizePolicy().hasHeightForWidth())
        self.moneyLabel.setSizePolicy(sizePolicy)
        self.moneyLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.moneyLabel.setObjectName("moneyLabel")
        self.moneyLayout.addWidget(self.moneyLabel)
        self.moneyBox = QtWidgets.QSpinBox(self.centralwidget)
        self.moneyBox.setMinimumSize(QtCore.QSize(0, 25))
        self.moneyBox.setMinimum(0)
        self.moneyBox.setMaximum(999999999)
        self.moneyBox.setProperty("value", 10000000)
        self.moneyBox.setObjectName("moneyBox")
        self.moneyLayout.addWidget(self.moneyBox)
        self.financeLayout.addLayout(self.moneyLayout)
        self.leverageLayout = QtWidgets.QVBoxLayout()
        self.leverageLayout.setObjectName("leverageLayout")
        self.leverageLabel = QtWidgets.QLabel(self.centralwidget)
        self.leverageLabel.setObjectName("leverageLabel")
        self.leverageLayout.addWidget(self.leverageLabel)
        self.leverageSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.leverageSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.leverageSpin.setMaximum(100.0)
        self.leverageSpin.setSingleStep(0.1)
        self.leverageSpin.setProperty("value", 1.0)
        self.leverageSpin.setObjectName("leverageSpin")
        self.leverageLayout.addWidget(self.leverageSpin)
        self.financeLayout.addLayout(self.leverageLayout)
        self.tvolLayout = QtWidgets.QVBoxLayout()
        self.tvolLayout.setObjectName("tvolLayout")
        self.tvolLabel = QtWidgets.QLabel(self.centralwidget)
        self.tvolLabel.setObjectName("tvolLabel")
        self.tvolLayout.addWidget(self.tvolLabel)
        self.tvolValLayout = QtWidgets.QHBoxLayout()
        self.tvolValLayout.setObjectName("tvolValLayout")
        self.tvolCheck = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvolCheck.sizePolicy().hasHeightForWidth())
        self.tvolCheck.setSizePolicy(sizePolicy)
        self.tvolCheck.setMinimumSize(QtCore.QSize(5, 0))
        self.tvolCheck.setText("")
        self.tvolCheck.setObjectName("tvolCheck")
        self.tvolValLayout.addWidget(self.tvolCheck)
        self.tvolSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.tvolSpin.setEnabled(False)
        self.tvolSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.tvolSpin.setMaximum(100.0)
        self.tvolSpin.setObjectName("tvolSpin")
        self.tvolValLayout.addWidget(self.tvolSpin)
        self.tvolLayout.addLayout(self.tvolValLayout)
        self.financeLayout.addLayout(self.tvolLayout)
        self.rateLayout = QtWidgets.QVBoxLayout()
        self.rateLayout.setObjectName("rateLayout")
        self.rateLabel = QtWidgets.QLabel(self.centralwidget)
        self.rateLabel.setObjectName("rateLabel")
        self.rateLayout.addWidget(self.rateLabel)
        self.rateSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rateSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.rateSpin.setObjectName("rateSpin")
        self.rateLayout.addWidget(self.rateSpin)
        self.financeLayout.addLayout(self.rateLayout)
        self.strategyLayout.addLayout(self.financeLayout)
        self.feeLayout = QtWidgets.QHBoxLayout()
        self.feeLayout.setContentsMargins(-1, -1, -1, 5)
        self.feeLayout.setObjectName("feeLayout")
        self.fiixfeeLayout = QtWidgets.QVBoxLayout()
        self.fiixfeeLayout.setObjectName("fiixfeeLayout")
        self.fixfeeLabel = QtWidgets.QLabel(self.centralwidget)
        self.fixfeeLabel.setObjectName("fixfeeLabel")
        self.fiixfeeLayout.addWidget(self.fixfeeLabel)
        self.fixfeeSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.fixfeeSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.fixfeeSpin.setMaximum(100000.0)
        self.fixfeeSpin.setObjectName("fixfeeSpin")
        self.fiixfeeLayout.addWidget(self.fixfeeSpin)
        self.feeLayout.addLayout(self.fiixfeeLayout)
        self.prcfeeLayout = QtWidgets.QVBoxLayout()
        self.prcfeeLayout.setObjectName("prcfeeLayout")
        self.prcLabel = QtWidgets.QLabel(self.centralwidget)
        self.prcLabel.setObjectName("prcLabel")
        self.prcfeeLayout.addWidget(self.prcLabel)
        self.prcfeeSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.prcfeeSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.prcfeeSpin.setObjectName("prcfeeSpin")
        self.prcfeeLayout.addWidget(self.prcfeeSpin)
        self.feeLayout.addLayout(self.prcfeeLayout)
        self.rebgapLayout = QtWidgets.QVBoxLayout()
        self.rebgapLayout.setContentsMargins(-1, -1, -1, 0)
        self.rebgapLayout.setObjectName("rebgapLayout")
        self.rebgapLabel = QtWidgets.QLabel(self.centralwidget)
        self.rebgapLabel.setObjectName("rebgapLabel")
        self.rebgapLayout.addWidget(self.rebgapLabel)
        self.rebgapSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rebgapSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.rebgapSpin.setObjectName("rebgapSpin")
        self.rebgapLayout.addWidget(self.rebgapSpin)
        self.feeLayout.addLayout(self.rebgapLayout)
        self.minWeightLayout = QtWidgets.QVBoxLayout()
        self.minWeightLayout.setObjectName("minWeightLayout")
        self.minWeightLabel = QtWidgets.QLabel(self.centralwidget)
        self.minWeightLabel.setObjectName("minWeightLabel")
        self.minWeightLayout.addWidget(self.minWeightLabel)
        self.minWeightSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.minWeightSpin.setMaximum(100.0)
        self.minWeightSpin.setObjectName("minWeightSpin")
        self.minWeightLayout.addWidget(self.minWeightSpin)
        self.feeLayout.addLayout(self.minWeightLayout)
        self.maxWeightLayout = QtWidgets.QVBoxLayout()
        self.maxWeightLayout.setObjectName("maxWeightLayout")
        self.maxWeightLabel = QtWidgets.QLabel(self.centralwidget)
        self.maxWeightLabel.setObjectName("maxWeightLabel")
        self.maxWeightLayout.addWidget(self.maxWeightLabel)
        self.maxWeightSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.maxWeightSpin.setMaximum(100.0)
        self.maxWeightSpin.setProperty("value", 100.0)
        self.maxWeightSpin.setObjectName("maxWeightSpin")
        self.maxWeightLayout.addWidget(self.maxWeightSpin)
        self.feeLayout.addLayout(self.maxWeightLayout)
        self.decimalLayout = QtWidgets.QVBoxLayout()
        self.decimalLayout.setObjectName("decimalLayout")
        self.decimalLabel = QtWidgets.QLabel(self.centralwidget)
        self.decimalLabel.setObjectName("decimalLabel")
        self.decimalLayout.addWidget(self.decimalLabel)
        self.decimalSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.decimalSpin.setMinimumSize(QtCore.QSize(0, 25))
        self.decimalSpin.setMinimum(1)
        self.decimalSpin.setMaximum(6)
        self.decimalSpin.setProperty("value", 2)
        self.decimalSpin.setObjectName("decimalSpin")
        self.decimalLayout.addWidget(self.decimalSpin)
        self.feeLayout.addLayout(self.decimalLayout)
        self.paramsLayout = QtWidgets.QVBoxLayout()
        self.paramsLayout.setObjectName("paramsLayout")
        self.integerCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.integerCheckBox.setMinimumSize(QtCore.QSize(0, 25))
        self.integerCheckBox.setChecked(True)
        self.integerCheckBox.setObjectName("integerCheckBox")
        self.paramsLayout.addWidget(self.integerCheckBox)
        self.covCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.covCheckBox.setMinimumSize(QtCore.QSize(0, 25))
        self.covCheckBox.setObjectName("covCheckBox")
        self.paramsLayout.addWidget(self.covCheckBox)
        self.feeLayout.addLayout(self.paramsLayout)
        self.strategyLayout.addLayout(self.feeLayout)
        self.periodsLayout = QtWidgets.QHBoxLayout()
        self.periodsLayout.setSpacing(5)
        self.periodsLayout.setObjectName("periodsLayout")
        self.estLayout = QtWidgets.QVBoxLayout()
        self.estLayout.setObjectName("estLayout")
        self.estPeriodLabel = QtWidgets.QLabel(self.centralwidget)
        self.estPeriodLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.estPeriodLabel.setObjectName("estPeriodLabel")
        self.estLayout.addWidget(self.estPeriodLabel)
        self.estboxLayot = QtWidgets.QHBoxLayout()
        self.estboxLayot.setContentsMargins(-1, -1, -1, 5)
        self.estboxLayot.setObjectName("estboxLayot")
        self.estPeriodSpin = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estPeriodSpin.sizePolicy().hasHeightForWidth())
        self.estPeriodSpin.setSizePolicy(sizePolicy)
        self.estPeriodSpin.setMinimumSize(QtCore.QSize(50, 25))
        self.estPeriodSpin.setMinimum(1)
        self.estPeriodSpin.setProperty("value", 1)
        self.estPeriodSpin.setObjectName("estPeriodSpin")
        self.estboxLayot.addWidget(self.estPeriodSpin)
        self.estTypeCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estTypeCombo.sizePolicy().hasHeightForWidth())
        self.estTypeCombo.setSizePolicy(sizePolicy)
        self.estTypeCombo.setMinimumSize(QtCore.QSize(0, 25))
        self.estTypeCombo.setEditable(False)
        self.estTypeCombo.setCurrentText("")
        self.estTypeCombo.setObjectName("estTypeCombo")
        self.estboxLayot.addWidget(self.estTypeCombo)
        self.estLayout.addLayout(self.estboxLayot)
        self.periodsLayout.addLayout(self.estLayout)
        self.rollLayout = QtWidgets.QVBoxLayout()
        self.rollLayout.setObjectName("rollLayout")
        self.rollPeriodLabel = QtWidgets.QLabel(self.centralwidget)
        self.rollPeriodLabel.setObjectName("rollPeriodLabel")
        self.rollLayout.addWidget(self.rollPeriodLabel)
        self.rollboxLayout = QtWidgets.QHBoxLayout()
        self.rollboxLayout.setContentsMargins(-1, -1, -1, 5)
        self.rollboxLayout.setObjectName("rollboxLayout")
        self.rollPeriodSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.rollPeriodSpin.setMinimumSize(QtCore.QSize(50, 25))
        self.rollPeriodSpin.setMinimum(1)
        self.rollPeriodSpin.setObjectName("rollPeriodSpin")
        self.rollboxLayout.addWidget(self.rollPeriodSpin)
        self.rollTypeCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rollTypeCombo.sizePolicy().hasHeightForWidth())
        self.rollTypeCombo.setSizePolicy(sizePolicy)
        self.rollTypeCombo.setMinimumSize(QtCore.QSize(0, 25))
        self.rollTypeCombo.setObjectName("rollTypeCombo")
        self.rollboxLayout.addWidget(self.rollTypeCombo)
        self.rollLayout.addLayout(self.rollboxLayout)
        self.periodsLayout.addLayout(self.rollLayout)
        self.ddLayout = QtWidgets.QVBoxLayout()
        self.ddLayout.setObjectName("ddLayout")
        self.ddCB = QtWidgets.QCheckBox(self.centralwidget)
        self.ddCB.setObjectName("ddCB")
        self.ddLayout.addWidget(self.ddCB)
        self.periodsLayout.addLayout(self.ddLayout)
        self.strategyLayout.addLayout(self.periodsLayout)
        self.stratbuttonsLayout = QtWidgets.QHBoxLayout()
        self.stratbuttonsLayout.setObjectName("stratbuttonsLayout")
        self.addStrategyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addStrategyBtn.setMinimumSize(QtCore.QSize(0, 25))
        self.addStrategyBtn.setObjectName("addStrategyBtn")
        self.stratbuttonsLayout.addWidget(self.addStrategyBtn)
        self.removeStrategyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.removeStrategyBtn.setMinimumSize(QtCore.QSize(0, 25))
        self.removeStrategyBtn.setObjectName("removeStrategyBtn")
        self.stratbuttonsLayout.addWidget(self.removeStrategyBtn)
        self.strategyLayout.addLayout(self.stratbuttonsLayout)
        self.strategyList = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strategyList.sizePolicy().hasHeightForWidth())
        self.strategyList.setSizePolicy(sizePolicy)
        self.strategyList.setMinimumSize(QtCore.QSize(800, 60))
        self.strategyList.setObjectName("strategyList")
        self.strategyLayout.addWidget(self.strategyList)
        self.mainLayout.addLayout(self.strategyLayout)
        self.horizontalLayout_2.addLayout(self.mainLayout)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.dataFileButton, self.dateColumnEdit)
        mainWindow.setTabOrder(self.dateColumnEdit, self.dateFormatEdit)
        mainWindow.setTabOrder(self.dateFormatEdit, self.startDatePicker)
        mainWindow.setTabOrder(self.startDatePicker, self.endDatePicker)
        mainWindow.setTabOrder(self.endDatePicker, self.estTypeCombo)
        mainWindow.setTabOrder(self.estTypeCombo, self.rollTypeCombo)
        mainWindow.setTabOrder(self.rollTypeCombo, self.removeStrategyBtn)
        mainWindow.setTabOrder(self.removeStrategyBtn, self.reportFileBtn)
        mainWindow.setTabOrder(self.reportFileBtn, self.reportFileEdit)
        mainWindow.setTabOrder(self.reportFileEdit, self.runTestButton)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "HRP Tester"))
        self.dataFileLabel.setText(_translate("mainWindow", "Data File Path"))
        self.dataFileButton.setText(_translate("mainWindow", "Open File"))
        self.rateFileLabel.setText(_translate("mainWindow", "Risk Free File Path"))
        self.rateFileButton.setText(_translate("mainWindow", "Open File"))
        self.dateColumnLabel.setText(_translate("mainWindow", "Column name with dates"))
        self.dateColumnEdit.setText(_translate("mainWindow", "Date"))
        self.dateFormatLabel.setText(_translate("mainWindow", "Date format"))
        self.dateFormatEdit.setText(_translate("mainWindow", "%Y-%m-%d"))
        self.startDateLabel.setText(_translate("mainWindow", "Start Date"))
        self.endDateLabel.setText(_translate("mainWindow", "End Date"))
        self.reportFileLabel.setText(_translate("mainWindow", "Report File Path"))
        self.reportFileBtn.setText(_translate("mainWindow", "Report Folder"))
        self.runTestButton.setText(_translate("mainWindow", "Test!"))
        self.moneyLabel.setText(_translate("mainWindow", "Initial balance"))
        self.leverageLabel.setText(_translate("mainWindow", "Max Leverage"))
        self.tvolLabel.setText(_translate("mainWindow", "Target volatility %"))
        self.rateLabel.setText(_translate("mainWindow", "Risk free rate"))
        self.fixfeeLabel.setText(_translate("mainWindow", "Fixed fee"))
        self.prcLabel.setText(_translate("mainWindow", "Fee %"))
        self.rebgapLabel.setText(_translate("mainWindow", "Rebalance gap %"))
        self.minWeightLabel.setText(_translate("mainWindow", "Min Weight"))
        self.maxWeightLabel.setText(_translate("mainWindow", "Max Weight"))
        self.decimalLabel.setText(_translate("mainWindow", "Weights rounding"))
        self.integerCheckBox.setText(_translate("mainWindow", "Integer position"))
        self.covCheckBox.setText(_translate("mainWindow", "OAS (robust cov matrix)"))
        self.estPeriodLabel.setText(_translate("mainWindow", "Estimation period"))
        self.rollPeriodLabel.setText(_translate("mainWindow", "Roll period"))
        self.ddCB.setText(_translate("mainWindow", "Downside deviation"))
        self.addStrategyBtn.setText(_translate("mainWindow", "Add Strategy"))
        self.removeStrategyBtn.setText(_translate("mainWindow", "Remove Strategy"))

